### ISSUE TITLE
Passing empty array

### ISSUE THREAD

**Issue by Whiz652** [maxenko/SodiumUE4#4]
Likely missing check for empty array in Decrypt String (and possibly other) method.

Passing empty encrypted array causes assertion failed.
[Empty Encrypted Log.txt](https://github.com/maxenko/SodiumUE4/files/1167447/Empty.Encrypted.Log.txt)

Passing empty public/private key array to Decrypt String method causes fatal error.
[Empty Key Log.txt](https://github.com/maxenko/SodiumUE4/files/1167446/Empty.Key.Log.txt)

**Comment by maxenko** [comment]
Bug fixed by @Whiz652
